User.create!(name: "Sara Mellott",
             email: "snmellott@gmail.com",
             password: "foobar",
             password_confirmation: "foobar",
             admin: true,
             activated: true,
             activated_at: Time.zone.now)
User.create!(name: "Will Westin",
             email: "wwestin@westinmedco.com",
             password: "foobar",
             password_confirmation: "foobar",
             activated: true,
             activated_at: Time.zone.now)
User.create!(name: "Brittany Campbell",
             email: "brittany@example.com",
             password: "foobar",
             password_confirmation: "foobar",
             activated: true,
             activated_at: Time.zone.now)
User.create!(name: "Bill Archer",
             email: "barcher@example.com",
             password: "foobar",
             password_confirmation: "foobar",
             activated: true,
             activated_at: Time.zone.now)
